check

diff --git a/.github/workflows/cypress.yaml b/.github/workflows/cypress.yaml
--- a/.github/workflows/cypress.yaml
+++ b/.github/workflows/cypress.yaml
@@ -11,11 +11,17 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Get latest deployment status
-        id: deployment_status
+        id: deployment_status_check
         run: |
           DEPLOYMENT_URL=$(curl -s "https://api.github.com/repos/${{ github.repository }}/deployments?environment=production&per_page=1" | jq -r '.[0].statuses_url')
           DEPLOYMENT_STATE=$(curl -s "$DEPLOYMENT_URL" | jq -r '.[0].state')
-          echo "::set-output name=deployment_state::$DEPLOYMENT_STATE"
+          echo "::setOutput name=deployment_state::$DEPLOYMENT_STATE"
+      
+      - name: Exit if deployment failed
+        if: ${{ steps.deployment_status_check.outputs.deployment_state != 'success' }}
+        run: |
+          echo "Deployment failed!"
+          exit 1
 
       - name: Run Cypress
         uses: cypress-io/github-action@v5
